name: Experimental test blog
markdown:       kramdown
redcarpet:
    extensions: ['smart']

highlighter:         rouge
fenced_code_blocks:  true

name:         Data Science Confidential
description:  Data Science Confidential
url:          https://testblog1.github.io
