markdown:       kramdown
redcarpet:
    extensions: ['smart']

highlighter:         rouge
kramdown: 
  input: GFM
  syntax_highlighter: rouge
#fenced_code_blocks:  true

name:         Data Science Confidential
description:  Data Science Confidential
url:          https://datascienceconfidential.github.io
baseurl:          /

title: Data Science Confidential
tagline: Data Science Confidential

paginate:     5
paginate_path: "/blog/page:num/"

comments: true
